//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Rentals = new HashSet<Rental>();
        }
    
        public int CarID { get; set; }
        public string CarType { get; set; }
        public string CarPhotoPath { get; set; }
        public decimal CarHorsepower { get; set; }
        public decimal CarCapacity { get; set; }
        public string CarMotorcode { get; set; }
        public decimal CarRentalPrice { get; set; }
        public decimal CarQuantity { get; set; }
        public string CarCategory { get; set; }
        public decimal CoordLat { get; set; }
        public decimal CoordLong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rental> Rentals { get; set; }
    }
}
