//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalServiceJoin
    {
        public int RsJoinID { get; set; }
        public Nullable<int> RentalID { get; set; }
        public string ServiceName { get; set; }
    
        public virtual Rental Rental { get; set; }
        public virtual Service Service { get; set; }
    }
}
